### PR TITLE
Fix binary testcases loading/encoding on browser side

### LINKED ISSUE #755: Binary test cases are not encoded properly by the browser
This issue has been mentionned on #749 and on the chat.

Binary test cases are not properly base64-encoded when being sent to Bugzilla.

### PR DESCRIPTION
**Pull request by EvaBardou**
Closes #755

### CODE REVIEW

File: server/frontend/src/components/Bugs/PublicationForm.vue [hunk 1]
```diff
@@ -780,12 +780,15 @@ export default {
           let content = this.testCaseContent;
           // If the testcase is binary we need to download it first
           if (this.entry.testcase_isbinary) {
-            content = await api.retrieveCrashTestCase(this.entry.id);
+            const resp = await api.retrieveCrashTestCaseBinary(this.entry.id);
+            content = new Uint8Array(resp.data);
```
Comment (La0) [inline server/frontend/src/components/Bugs/PublicationForm.vue:784]: You should directly do that step in `retrieveCrashTestCaseBinary` so the internal API stays consistent (we get usable payloads from the `api.js` module)

**Review by La0 — CHANGES_REQUESTED** [review]
